"""Added answers column

Revision ID: 72afbb2ec51a
Revises: 9b47b2abc41f
Create Date: 2023-02-27 22:38:06.930611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72afbb2ec51a'
down_revision = '9b47b2abc41f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
