"""Fixed the questions_id column

Revision ID: 77df5700c81a
Revises: f5ea3cccda69
Create Date: 2023-02-28 01:08:47.200113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77df5700c81a'
down_revision = 'f5ea3cccda69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('questions_id', sa.Integer(), nullable=False))
    op.drop_constraint('answers_questiond_id_fkey', 'answers', type_='foreignkey')
    op.create_foreign_key(None, 'answers', 'questions', ['questions_id'], ['id'], ondelete='CASCADE')
    op.drop_column('answers', 'questiond_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('questiond_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.create_foreign_key('answers_questiond_id_fkey', 'answers', 'questions', ['questiond_id'], ['id'], ondelete='CASCADE')
    op.drop_column('answers', 'questions_id')
    # ### end Alembic commands ###
