"""Added answers column v2

Revision ID: f5ea3cccda69
Revises: 72afbb2ec51a
Create Date: 2023-02-27 22:40:39.344343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ea3cccda69'
down_revision = '72afbb2ec51a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
